- name: add record
  hosts: dns

  tasks:
  - name: Create switches records
    win_dns_record:
      name: "{{hostvars[item].sn_name}}"
      type: "A"
      value: "{{hostvars[item].sn_ip_address}}"
      zone: "mobiz.local"
    loop: "{{ groups['switches'] }}"
