- name: add record
  hosts: dns

  tasks:
  - name: Create switches records
    win_dns_record:
      name: "{{hostvars[item].sn_name}}"
      type: "A"
      value: "{{hostvars[item].sn_ip_address}}"
      zone: "mobiz.local"
    loop: "{{ groups['switches'] }}"


  - name: Create PTR record for switches
    win_dns_record:
      name: "{{hostvars[item].sn_ip_address.split('.')[3] | join('.')}}"
      type: "PTR"
      value: "{{hostvars[item].sn_name}}"
      zone: "0.10.10.in-addr.arpa"
    loop: "{{ groups['switches'] }}"