- name: add record
  hosts: all 

  tasks:
  - name: Create switches records
    win_dns_record:
      name: "{{item}}"
      type: "A"
      value: "{{hostvars[item].ansible_host}}"
      zone: "mobiz.local"
    loop: "{{ groups['switches'] }}"



  - name: Create routers records
    win_dns_record:
      name: "{{item}}"
      type: "A"
      value: "{{hostvars[item].ansible_host}}"
      zone: "mobiz.local"
    loop: "{{ groups['routers'] }}"
