- name: add record
  hosts: all 

  tasks:
  - name: Create database server record
    community.windows.win_dns_record:
      name: "db.mobiz.local"
      type: "A"
      value: "10.1.1.1"
      zone: "mobiz.local"
